"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "bn";

interface AppContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

// Bengali translations — nested structure accessed via dot notation
// English is pass-through (the key's last segment IS the English text)
const bn: Record<string, string> = {
  // ============ COMMON ============
  "common.identity_verification_required": "পরিচয় যাচাইকরণ প্রয়োজন",
  "common.identity_verification_desc": "প্ল্যাটফর্মের সুবিধা আনলক করতে সেটিংসে আপনার জাতীয় পরিচয়পত্রের বিবরণ জমা দিন।",
  "common.go_to_settings": "সেটিংসে যান",
  "common.verification_required": "যাচাইকরণ প্রয়োজন",
  "common.logout": "লগ আউট",
  "common.profile": "প্রোফাইল",
  "common.settings": "সেটিংস",
  "common.view_all": "সব দেখুন",
  "common.manage_all": "সব পরিচালনা করুন",
  "common.not_provided": "দেওয়া হয়নি",
  "common.network_contributor": "নেটওয়ার্ক অবদানকারী",
  "common.network_partner": "নেটওয়ার্ক অংশীদার",
  "common.worker_role": "কর্মী",
  "common.employer_role": "নিয়োগকর্তা",
  "common.anonymous_worker": "অজ্ঞাত কর্মী",
  "common.anonymous_employer": "অজ্ঞাত নিয়োগকর্তা",
  "common.no_biography_worker": "কোনো পরিচিতি দেওয়া হয়নি। আপনার দক্ষতা সম্পর্কে নিয়োগকর্তাদের জানাতে সেটিংস আপডেট করুন।",
  "common.no_biography_employer": "কোনো পরিচিতি দেওয়া হয়নি। কর্মীদের আপনার পোস্ট করা কাজের ধরন সম্পর্কে জানাতে সেটিংস আপডেট করুন।",
  "common.badge_live": "লাইভ",
  "common.badge_paused": "বিরতি",
  "common.badge_completed": "সম্পন্ন",
  "common.badge_new": "নতুন",
  "common.lifetime": "আজীবন",
  "common.auto_converted": "স্বয়ংক্রিয়ভাবে রূপান্তরিত",
  "common.per_worker": "প্রতি কর্মী",
  "common.progress": "অগ্রগতি",
  "common.id_verified": "আইডি যাচাইকৃত",
  "common.saved_successfully": "সফলভাবে সংরক্ষিত হয়েছে",
  "common.no_posts_yet": "আপনি এখনো কোনো কাজ পোস্ট করেননি।",
  "common.create_first_post": "আপনার প্রথম পোস্ট তৈরি করুন",

  // ============ SIDEBAR ============
  "sidebar.overview": "ওভারভিউ",
  "sidebar.browse_jobs": "কাজ খুঁজুন",
  "sidebar.my_submissions": "আমার জমা",
  "sidebar.earnings_hub": "উপার্জন কেন্দ্র",
  "sidebar.profile": "প্রোফাইল",
  "sidebar.settings": "সেটিংস",
  "sidebar.manage_jobs": "কাজ পরিচালনা করুন",
  "sidebar.review_submissions": "জমা পর্যালোচনা করুন",
  "sidebar.wallet": "ওয়ালেট",
  "sidebar.post_new_job": "নতুন কাজ পোস্ট করুন",
  "sidebar.deposit_funds": "তহবিল জমা করুন",

  // ============ DASHBOARD (Worker Overview) ============
  "dashboard.welcome": "স্বাগতম,",
  "dashboard.today_activity": "আজ আপনার মাইক্রো-জবগুলির সাথে কী ঘটছে তা এখানে রয়েছে।",
  "dashboard.total_earned": "মোট আয়",
  "dashboard.pending_review": "পর্যালোচনা বাকি",
  "dashboard.success_rate": "সাফল্যের হার",
  "dashboard.awaiting_employer": "নিয়োগকর্তার পদক্ষেপের অপেক্ষায়",
  "dashboard.excellent_standing": "চমৎকার অবস্থান",
  "dashboard.recent_submissions": "সাম্প্রতিক জমা",
  "dashboard.available_jobs": "উপলব্ধ কাজ",
  "dashboard.no_jobs_available": "কোনো কাজ উপলব্ধ নেই।",
  "dashboard.no_recent_activity": "কোনো সাম্প্রতিক কার্যকলাপ নেই।",
  "dashboard.streak_days": "৩ দিনের ধারা",
  "dashboard.lifetime_earnings": "আজীবন উপার্জন",
  "dashboard.slots_left": "স্লট বাকি",
  "dashboard.only_left": "মাত্র {{count}}টি বাকি!",

  // ============ EMPLOYER DASHBOARD ============
  "employer_dashboard.employer_portal": "নিয়োগকর্তা পোর্টাল",
  "employer_dashboard.subtitle": "আপনার কাজের পোস্টিং পরিচালনা করুন এবং আবেদন পর্যালোচনা করুন।",
  "employer_dashboard.stat_total_spent": "মোট ব্যয়",
  "employer_dashboard.stat_active_campaigns": "সক্রিয় ক্যাম্পেইন",
  "employer_dashboard.stat_pending_approvals": "অনুমোদন বাকি",
  "employer_dashboard.stat_engagement": "এনগেজমেন্ট",
  "employer_dashboard.stat_cost_per_completion": "প্রতি সম্পন্নে খরচ",
  "employer_dashboard.stat_lifetime": "আজীবন",
  "employer_dashboard.stat_currently_open": "বর্তমানে চালু",
  "employer_dashboard.stat_action_required": "পদক্ষেপ প্রয়োজন",
  "employer_dashboard.stat_total_submissions": "মোট জমা",
  "employer_dashboard.stat_avg_efficiency": "গড় দক্ষতা",
  "employer_dashboard.recent_postings": "সাম্প্রতিক পোস্টিং",
  "employer_dashboard.post_new_job": "নতুন কাজ পোস্ট করুন",
  "employer_dashboard.post_new": "নতুন পোস্ট",

  // ============ MANAGE JOBS ============
  "manage_jobs.title": "কাজ পরিচালনা করুন",
  "manage_jobs.target_url": "টার্গেট লিংক",
  "manage_jobs.campaign_progress": "ক্যাম্পেইনের অগ্রগতি",

  // ============ REVIEW SUBMISSIONS ============
  "review_submissions.title": "জমা পর্যালোচনা করুন",
  "review_submissions.subtitle": "কর্মীর প্রমাণ মূল্যায়ন করুন এবং নিরাপদে পেমেন্ট ছাড় করুন।",
  "review_submissions.no_submissions": "এই মুহূর্তে পর্যালোচনার জন্য কোনো জমা নেই।",
  "review_submissions.job_category": "কাজের বিভাগ",
  "review_submissions.worker_proof": "কর্মীর প্রমাণ জমা দেওয়া হয়েছে:",
  "review_submissions.payment_released": "কর্মীকে পেমেন্ট ছাড় দেওয়া হয়েছে।",
  "review_submissions.escrow_amount": "এসক্রো পরিমাণ",
  "review_submissions.btn_approve": "অনুমোদন এবং অর্থ প্রদান",
  "review_submissions.waiting_proof": "কর্মীর প্রমাণের জন্য অপেক্ষা করা হচ্ছে...",
  "review_submissions.btn_approved": "অনুমোদিত",

  // ============ EMPLOYER WALLET ============
  "employer_wallet.title": "আর্থিক কেন্দ্র",
  "employer_wallet.subtitle": "আপনার তহবিল এবং প্ল্যাটফর্ম পেমেন্ট পরিচালনা করুন।",
  "employer_wallet.current_balance": "বর্তমান ব্যালেন্স",
  "employer_wallet.btn_deposit": "তহবিল জমা করুন",
  "employer_wallet.btn_configure_payment": "পেমেন্ট পদ্ধতি সেট করুন",
  "employer_wallet.total_spent": "মোট ব্যয়",
  "employer_wallet.active_escrow": "সক্রিয় এসক্রো",
  "employer_wallet.locked_in_jobs": "সক্রিয় কাজে লক করা",
  "employer_wallet.recent_activity": "সাম্প্রতিক কার্যকলাপ",
  "employer_wallet.no_spending": "কোনো সাম্প্রতিক ব্যয় কার্যকলাপ নেই।",
  "employer_wallet.payment_prefix": "পেমেন্ট:",

  // ============ PROFILE ============
  "profile.title": "প্রোফাইল",
  "profile.subtitle": "আপনার প্ল্যাটফর্ম পরিচয় এবং অ্যাকাউন্টের অবস্থা দেখুন।",

  // ============ SETTINGS ============
  "settings.title": "সেটিংস",
  "settings.subtitle": "আপনার অ্যাকাউন্টের পছন্দ এবং নিরাপত্তা পরিচালনা করুন।",
  "settings.tab_account": "অ্যাকাউন্ট ও প্রোফাইল",
  "settings.tab_payment": "পেমেন্ট পদ্ধতি",
  "settings.tab_security": "নিরাপত্তা",
  "settings.tab_notifications": "বিজ্ঞপ্তি",
  "settings.tab_localization": "স্থানীয়করণ",
  "settings.section_account": "অ্যাকাউন্ট ও প্রোফাইল",
  "settings.full_name": "পুরো নাম",
  "settings.full_name_placeholder": "যেমন: জানে ডো",
  "settings.email_address": "ইমেইল ঠিকানা",
  "settings.phone_number": "ফোন নম্বর",
  "settings.nid_verification": "জাতীয় পরিচয়পত্র যাচাই",
  "settings.nid_placeholder": "১০ বা ১৩ সংখ্যার NID নম্বর লিখুন",
  "settings.upload_nid_front": "NID-এর সামনের অংশ আপলোড করুন",
  "settings.upload_nid_back": "NID-এর পিছনের অংশ আপলোড করুন",
  "settings.click_or_drop": "ক্লিক করুন বা ছবি ড্র্যাগ করুন",
  "settings.image_requirements": "ছবি স্পষ্ট ও পাঠযোগ্য হতে হবে। JPG বা PNG সর্বোচ্চ ৫MB।",
  "settings.btn_save_account": "অ্যাকাউন্ট সংরক্ষণ করুন",
  "settings.payment_gateways": "পেমেন্ট গেটওয়ে",
  "settings.bkash_label": "বিকাশ নম্বর (ব্যক্তিগত)",
  "settings.nagad_label": "নগদ নম্বর (ব্যক্তিগত)",
  "settings.btn_save_methods": "পদ্ধতি সংরক্ষণ করুন",
  "settings.security_title": "নিরাপত্তা",
  "settings.current_password": "বর্তমান পাসওয়ার্ড",
  "settings.new_password": "নতুন পাসওয়ার্ড",
  "settings.confirm_password": "নতুন পাসওয়ার্ড নিশ্চিত করুন",
  "settings.btn_update_password": "পাসওয়ার্ড আপডেট করুন",
  "settings.notifications_title": "বিজ্ঞপ্তি সেটিংস",
  "settings.email_notifications": "ইমেইল বিজ্ঞপ্তি",
  "settings.email_notif_desc": "কাজের আপডেট এবং অ্যাকাউন্ট নিরাপত্তার জন্য সতর্কতা পান।",
  "settings.push_notifications": "পুশ বিজ্ঞপ্তি",
  "settings.push_notif_desc": "দ্রুত আপডেটের জন্য আপনার ব্রাউজারে রিয়েল-টাইম সতর্কতা।",
  "settings.localization_title": "স্থানীয়করণ",
  "settings.language": "ভাষা",
  "settings.timezone": "সময় অঞ্চল",
  "settings.btn_save_preferences": "পছন্দ সংরক্ষণ করুন",

  // ============ BROWSE JOBS ============
  "browse_jobs.title": "কাজ খুঁজুন",
  "browse_jobs.subtitle": "নেটওয়ার্কে আপনার পরবর্তী মাইক্রো-জব খুঁজুন।",
  "browse_jobs.search_placeholder": "শিরোনাম বা বিভাগ দিয়ে খুঁজুন...",
  "browse_jobs.filter_all": "সব",
  "browse_jobs.filter_other": "অন্যান্য",
  "browse_jobs.action_label": "কাজ:",
  "browse_jobs.reward_label": "পুরস্কার:",
  "browse_jobs.slots_left": "স্লট বাকি",
  "browse_jobs.btn_applied": "আবেদন করা হয়েছে",
  "browse_jobs.btn_apply_now": "এখনই আবেদন করুন",
  "browse_jobs.btn_verify_to_apply": "যাচাই করে আবেদন করুন",
  "browse_jobs.no_match": "আপনার অনুসন্ধানের সাথে কোনো কাজ মেলেনি।",

  // ============ SUBMISSIONS ============
  "submissions.title": "আমার জমা",
  "submissions.subtitle": "আপনার সক্রিয় কাজগুলি ট্র্যাক করুন এবং কাজের প্রমাণ জমা দিন।",
  "submissions.no_submissions": "আপনি এখনো কোনো কাজে আবেদন করেননি।",
  "submissions.start_browsing": "ব্রাউজ শুরু করুন",
  "submissions.required_proof": "প্রয়োজনীয় প্রমাণ:",
  "submissions.proof_placeholder": "লিংক দিন অথবা আপনার প্রমাণ বর্ণনা করুন...",
  "submissions.btn_submit_proof": "প্রমাণ জমা দিন",
  "submissions.proof_under_review": "আপনার প্রমাণ পর্যালোচনায় আছে।",
  "submissions.job_completed_paid": "কাজ সম্পন্ন ও পরিশোধিত!",
  "submissions.payment_released_desc": "নিয়োগকর্তা আপনার কাজ অনুমোদন করেছেন এবং অর্থ আপনার ওয়ালেটে যোগ হয়েছে।",
  "submissions.rate_employer": "নিয়োগকর্তাকে রেটিং দিন",
  "submissions.rejection_title": "জমা প্রত্যাখ্যাত",
  "submissions.rejection_desc": "নিয়োগকর্তা আপনার প্রমাণ প্রত্যাখ্যান করেছেন। আপনি যদি মনে করেন এটি অন্যায়, আপনি আবেদন করতে পারেন।",
  "submissions.btn_appeal": "সিদ্ধান্তের বিরুদ্ধে আবেদন",
  "submissions.in_dispute": "বিরোধ নিষ্পত্তিতে",
  "submissions.dispute_desc": "প্ল্যাটফর্ম অ্যাডমিনরা বর্তমানে আপনার আবেদন এবং নিয়োগকর্তার প্রত্যাখ্যান পর্যালোচনা করছেন।",

  // ============ EARNINGS (Worker Wallet) ============
  "earnings.title": "উপার্জন কেন্দ্র",
  "earnings.subtitle": "আপনার উপার্জন পরিচালনা করুন এবং স্থানীয় পদ্ধতিতে উত্তোলন করুন।",
  "earnings.available_balance": "উপলব্ধ ব্যালেন্স",
  "earnings.lifetime_earnings": "আজীবন উপার্জন",
  "earnings.funds_in_review": "পর্যালোচনাধীন তহবিল",
  "earnings.locked_in_jobs": "সক্রিয় কাজে লক করা",
  "earnings.btn_withdraw": "উত্তোলন করুন",
  "earnings.btn_configure_payout": "পেমেন্ট পদ্ধতি সেট করুন",
  "earnings.recent_activity": "সাম্প্রতিক কার্যকলাপ",

  // ============ DEPOSIT MODAL ============
  "deposit.title": "তহবিল জমা করুন",
  "deposit.subtitle": "নিরাপদে মাইক্রো-জবের জন্য আপনার নিয়োগকর্তা ওয়ালেটে তহবিল যোগ করুন।",
  "deposit.select_method": "পেমেন্ট পদ্ধতি নির্বাচন করুন",
  "deposit.send_money_instruction": "আমাদের অফিসিয়াল ব্যক্তিগত নম্বরে টাকা পাঠান:",
  "deposit.amount_placeholder": "জমার পরিমাণ (৳)",
  "deposit.trxid_placeholder": "লেনদেন আইডি (TrxID)",
  "deposit.btn_confirm": "যাচাই করুন এবং জমা দিন",
  "deposit.verified": "জমা যাচাই হয়েছে!",
  "deposit.funds_added": "আপনার ব্যালেন্সে তহবিল যোগ করা হয়েছে।",
};

// English translations — human-readable values for dot-notation keys
const en: Record<string, string> = {
  "common.identity_verification_required": "Identity Verification Required",
  "common.identity_verification_desc": "You must submit your National ID details in Settings to unlock platform features.",
  "common.go_to_settings": "Go to Settings",
  "common.verification_required": "Verification Required",
  "common.logout": "Sign Out",
  "common.profile": "Profile",
  "common.settings": "Settings",
  "common.view_all": "View all",
  "common.manage_all": "Manage all",
  "common.not_provided": "Not provided",
  "common.network_contributor": "Network Contributor",
  "common.network_partner": "Network Partner",
  "common.worker_role": "Worker",
  "common.employer_role": "Employer",
  "common.anonymous_worker": "Anonymous Worker",
  "common.anonymous_employer": "Anonymous Employer",
  "common.no_biography_worker": "No biography provided. Update your settings to add a bio and tell employers more about your skills.",
  "common.no_biography_employer": "No biography provided. Update your settings to tell workers about the types of jobs you post.",
  "common.badge_live": "LIVE",
  "common.badge_paused": "PAUSED",
  "common.badge_completed": "COMPLETED",
  "common.badge_new": "NEW",
  "common.lifetime": "Lifetime",
  "common.auto_converted": "Auto-converted",
  "common.per_worker": "per worker",
  "common.progress": "Progress",
  "common.id_verified": "ID Verified",
  "common.saved_successfully": "Saved Successfully",
  "common.no_posts_yet": "You haven't posted any jobs yet.",
  "common.create_first_post": "Create your first post",
  "sidebar.overview": "Overview",
  "sidebar.browse_jobs": "Browse Jobs",
  "sidebar.my_submissions": "My Submissions",
  "sidebar.earnings_hub": "Earnings Hub",
  "sidebar.profile": "Profile",
  "sidebar.settings": "Settings",
  "sidebar.manage_jobs": "Manage Jobs",
  "sidebar.review_submissions": "Review Submissions",
  "sidebar.wallet": "Wallet",
  "sidebar.post_new_job": "Post New Job",
  "sidebar.deposit_funds": "Deposit Funds",
  "dashboard.welcome": "Welcome back,",
  "dashboard.today_activity": "Here's what's happening with your micro-jobs today.",
  "dashboard.total_earned": "Total Earned",
  "dashboard.pending_review": "Pending Review",
  "dashboard.success_rate": "Success Rate",
  "dashboard.awaiting_employer": "Awaiting employer action",
  "dashboard.excellent_standing": "Excellent standing",
  "dashboard.recent_submissions": "Recent Submissions",
  "dashboard.available_jobs": "Available Jobs",
  "dashboard.no_jobs_available": "No jobs available.",
  "dashboard.no_recent_activity": "No recent activity.",
  "dashboard.streak_days": "3 Day Streak",
  "dashboard.lifetime_earnings": "Lifetime earnings",
  "dashboard.slots_left": "slots left",
  "employer_dashboard.employer_portal": "Employer Portal",
  "employer_dashboard.subtitle": "Manage your job postings and review applications.",
  "employer_dashboard.stat_total_spent": "TOTAL SPENT",
  "employer_dashboard.stat_active_campaigns": "ACTIVE CAMPAIGNS",
  "employer_dashboard.stat_pending_approvals": "PENDING APPROVALS",
  "employer_dashboard.stat_engagement": "ENGAGEMENT",
  "employer_dashboard.stat_cost_per_completion": "Cost Per Completion",
  "employer_dashboard.stat_lifetime": "Lifetime",
  "employer_dashboard.stat_currently_open": "Currently open",
  "employer_dashboard.stat_action_required": "Action required",
  "employer_dashboard.stat_total_submissions": "Total submissions",
  "employer_dashboard.stat_avg_efficiency": "Avg. efficiency",
  "employer_dashboard.recent_postings": "Recent Postings",
  "employer_dashboard.post_new_job": "Post New Job",
  "employer_dashboard.post_new": "Post New",
  "manage_jobs.title": "Manage Jobs",
  "manage_jobs.target_url": "Target URL",
  "manage_jobs.campaign_progress": "Campaign Progress",
  "review_submissions.title": "Review Submissions",
  "review_submissions.subtitle": "Evaluate worker proofs and release payments securely.",
  "review_submissions.no_submissions": "No submissions to review right now.",
  "review_submissions.job_category": "Job Category",
  "review_submissions.worker_proof": "Worker Proof Submitted:",
  "review_submissions.payment_released": "Payment released to worker.",
  "review_submissions.escrow_amount": "Escrow Amount",
  "review_submissions.btn_approve": "Approve & Pay",
  "review_submissions.waiting_proof": "Waiting for worker proof...",
  "review_submissions.btn_approved": "Approved",
  "employer_wallet.title": "Financial Hub",
  "employer_wallet.subtitle": "Manage your funds and platform payments.",
  "employer_wallet.current_balance": "Current Balance",
  "employer_wallet.btn_deposit": "Deposit Funds",
  "employer_wallet.btn_configure_payment": "Configure Payment Methods",
  "employer_wallet.total_spent": "Total Spent",
  "employer_wallet.active_escrow": "Active Escrow",
  "employer_wallet.locked_in_jobs": "Locked in active jobs",
  "employer_wallet.recent_activity": "Recent Activity",
  "employer_wallet.no_spending": "No recent spending activity.",
  "employer_wallet.payment_prefix": "Payment:",
  "profile.title": "Your Profile",
  "profile.subtitle": "View your platform identity and account status.",
  "settings.title": "Settings",
  "settings.subtitle": "Manage your account preferences and security.",
  "settings.tab_account": "Account & Profile",
  "settings.tab_payment": "Payment Methods",
  "settings.tab_security": "Security",
  "settings.tab_notifications": "Notifications",
  "settings.tab_localization": "Localization",
  "settings.section_account": "Account & Profile",
  "settings.full_name": "Full Name",
  "settings.full_name_placeholder": "e.g. John Doe",
  "settings.email_address": "Email Address",
  "settings.phone_number": "Phone Number",
  "settings.nid_verification": "NID Verification",
  "settings.nid_placeholder": "Enter 10 or 13 digit NID Number",
  "settings.upload_nid_front": "Upload NID Front Part",
  "settings.upload_nid_back": "Upload NID Back Part",
  "settings.click_or_drop": "Click or drop image",
  "settings.image_requirements": "Images must be clear and readable. JPG or PNG max 5MB.",
  "settings.btn_save_account": "Save Account",
  "settings.payment_gateways": "Payment Gateways",
  "settings.bkash_label": "bKash Number (Personal)",
  "settings.nagad_label": "Nagad Number (Personal)",
  "settings.btn_save_methods": "Save Methods",
  "settings.security_title": "Security",
  "settings.current_password": "Current Password",
  "settings.new_password": "New Password",
  "settings.confirm_password": "Confirm New Password",
  "settings.btn_update_password": "Update Password",
  "settings.notifications_title": "Notification Preferences",
  "settings.email_notifications": "Email Notifications",
  "settings.email_notif_desc": "Receive alerts for job updates and account security.",
  "settings.push_notifications": "Push Notifications",
  "settings.push_notif_desc": "Real-time alerts in your browser for fast updates.",
  "settings.localization_title": "Localization",
  "settings.language": "Language",
  "settings.timezone": "Timezone",
  "settings.btn_save_preferences": "Save Preferences",
  "browse_jobs.title": "Browse Jobs",
  "browse_jobs.subtitle": "Find your next micro-job in the network.",
  "browse_jobs.search_placeholder": "Search by title or category...",
  "browse_jobs.filter_all": "All",
  "browse_jobs.filter_other": "Other",
  "browse_jobs.slots_left": "slots left",
  "browse_jobs.btn_applied": "Applied",
  "browse_jobs.btn_apply_now": "Apply Now",
  "browse_jobs.btn_verify_to_apply": "Verify to Apply",
  "browse_jobs.no_match": "No jobs matched your search.",
  "submissions.title": "My Submissions",
  "submissions.subtitle": "Track your active jobs and submit proof of work.",
  "submissions.no_submissions": "You haven't applied to any jobs yet.",
  "submissions.start_browsing": "Start browsing",
  "submissions.required_proof": "Required Proof:",
  "submissions.proof_placeholder": "Enter link or describe your proof...",
  "submissions.btn_submit_proof": "Submit Proof",
  "submissions.proof_under_review": "Your proof is under review.",
  "submissions.job_completed_paid": "Job Completed & Paid!",
  "submissions.payment_released_desc": "The employer approved your work and the funds have been added to your wallet.",
  "submissions.rate_employer": "Rate Employer",
  "submissions.rejection_title": "Submission Rejected",
  "submissions.rejection_desc": "The employer has rejected your proof. If you believe this is unfair, you can appeal.",
  "submissions.btn_appeal": "Appeal Decision",
  "submissions.in_dispute": "In Dispute Resolution",
  "submissions.dispute_desc": "Platform admins are currently reviewing your appeal and the employer's rejection.",
  "earnings.title": "Earnings Hub",
  "earnings.subtitle": "Manage your earnings and withdraw to your local methods.",
  "earnings.available_balance": "Available Balance",
  "earnings.lifetime_earnings": "Lifetime Earnings",
  "earnings.funds_in_review": "Funds In Review",
  "earnings.locked_in_jobs": "Locked in active jobs",
  "earnings.btn_withdraw": "Withdraw Funds",
  "earnings.btn_configure_payout": "Configure Payout Methods",
  "earnings.recent_activity": "Recent Activity",
  "deposit.title": "Deposit Funds",
  "deposit.subtitle": "Add funds to your employer wallet to pay for micro-jobs securely.",
  "deposit.select_method": "Select Payment Method",
  "deposit.send_money_instruction": "Please Send Money to our official personal number:",
  "deposit.amount_placeholder": "Deposit Amount (৳)",
  "deposit.trxid_placeholder": "Transaction ID (TrxID)",
  "deposit.btn_confirm": "Verify & Deposit",
  "deposit.verified": "Deposit Verified!",
  "deposit.funds_added": "Funds have been added to your balance.",
};

const translations: Record<string, Record<string, string>> = { en, bn };

const AppContext = createContext<AppContextType | undefined>(undefined);

export function AppProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang) setLanguage(savedLang);
    setMounted(true);
  }, []);

  useEffect(() => {
    if (!mounted) return;
    localStorage.setItem("language", language);
  }, [language, mounted]);

  const toggleLanguage = () => setLanguage(prev => prev === "en" ? "bn" : "en");

  const t = (key: string): string => {
    if (!mounted) return en[key] || key;
    const dict = translations[language];
    return dict?.[key] || en[key] || key;
  };

  return (
    <AppContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (context === undefined) {
    throw new Error("useApp must be used within an AppProvider");
  }
  return context;
}
